const content = {
        input:[
            {
                lable:'Card_number',
                name:'card_number',
                type:"text", 
        },
        {
            lable:'Username',
            name:'username',
            type:"text", 
        },
        {
            lable:'Exp_date',
            name:'exp_date',
            type:"date", 
        },
        {
            lable:'Cvv',
            name:'cvv',
            type:"text", 
        },
        {
            lable:'Checkbox',
            name:'checkbox',
            type:"checkbox", 
        },
    ],
};
export default content;